dist: bionic
language: python
python: 
  - "3.7"
services:
  - xvfb
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - pip install -r test-requirements.txt
script:
  - xvfb-run make test
  - python manage.py test lists accounts
  - python manage.py test functional_tests
