from django.contrib.auth  import get_user_model
from django.test import TestCase

# UsserModel is imported va get_user_model
from accounts.models import Token

User = get_user_model()

EMAIL = 'frantatrabanta@example.com'


class UserModelTest(TestCase):

    def test_user_is_valid_with_email_only(self):
        user = User(email=EMAIL)
        user.full_clean()

    def test_user_has_email_as_primary_key(self):
        user = User(email=EMAIL)
        self.assertEqual(user.pk, EMAIL)


class TokenModelTest(TestCase):

    def test_links_user_with_autogenerated_id(self):
        token1 = Token.objects.create(email='first@mail.com')
        token2 = Token.objects.create(email='second@mail.com')
        self.assertNotEqual(token1.uid, token2.uid)
